<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { BellRing, Mail, Search, Trash2 } from '@lucide/vue'
import { LocalApi, type EmailSettings, type Friend, type NotificationDelivery, type PresenceWatchRule } from './api'
const props=defineProps<{friends:Friend[]}>();const api=new LocalApi();const query=ref('');const watches=ref<PresenceWatchRule[]>([]);const deliveries=ref<NotificationDelivery[]>([]);const email=ref<EmailSettings>({enabled:false,host:'',port:587,security:'starttls',username:'',from:'',to:'',configured:false,password:''});const busy=ref('');const message=ref('')
const watchedIDs=computed(()=>new Set(watches.value.map(x=>x.userId)));const candidates=computed(()=>props.friends.filter(x=>!watchedIDs.value.has(x.id)&&(!query.value||`${x.displayName} ${x.id}`.toLowerCase().includes(query.value.toLowerCase()))).slice(0,80))
async function load(){await api.bootstrap();[watches.value,email.value,deliveries.value]=await Promise.all([api.presenceWatches(),api.presenceEmail(),api.presenceDeliveries()])}
async function add(friend:Friend){busy.value=friend.id;try{watches.value.push(await api.savePresenceWatch({userId:friend.id,displayName:friend.displayName,notifyOnline:true,notifyOffline:true,desktopEnabled:true,emailEnabled:false,currentState:friend.online?'online':'offline'}))}finally{busy.value=''}}
async function save(item:PresenceWatchRule){busy.value=item.userId;try{const saved=await api.savePresenceWatch({...item});watches.value=watches.value.map(x=>x.userId===saved.userId?saved:x)}finally{busy.value=''}}
async function remove(item:PresenceWatchRule){busy.value=item.userId;try{await api.deletePresenceWatch(item.userId);watches.value=watches.value.filter(x=>x.userId!==item.userId)}finally{busy.value=''}}
async function saveEmail(test=false){busy.value='email';message.value='';try{email.value=await api.savePresenceEmail(email.value);email.value.password='';if(test){await api.testPresenceEmail();message.value='测试邮件已发送'}else message.value='已保存'}catch(e){message.value=e instanceof Error?e.message:'操作失败'}finally{busy.value=''}}
onMounted(()=>load().catch(e=>message.value=e instanceof Error?e.message:'加载失败'))
</script>
<template><section class="presence-view wide-view"><div class="presence-toolbar"><div><h2><BellRing :size="20"/> 好友上线提醒</h2><span>{{ watches.length }} 位关注</span></div><label><Search :size="16"/><input v-model="query" placeholder="搜索好友或 ID"/></label></div><div class="presence-columns"><article class="presence-card"><h3>关注列表</h3><div v-if="watches.length" class="watch-list"><div v-for="item in watches" :key="item.userId" class="watch-row"><strong>{{ item.displayName }}</strong><label><input v-model="item.notifyOnline" type="checkbox" @change="save(item)"/>上线</label><label><input v-model="item.notifyOffline" type="checkbox" @change="save(item)"/>下线</label><label><input v-model="item.desktopEnabled" type="checkbox" @change="save(item)"/>托盘</label><label><input v-model="item.emailEnabled" type="checkbox" @change="save(item)"/>邮件</label><button title="取消关注" @click="remove(item)"><Trash2 :size="15"/></button></div></div><div v-else class="empty-compact">先从右侧添加好友</div></article><article class="presence-card"><h3>添加好友</h3><div class="candidate-list"><button v-for="friend in candidates" :key="friend.id" :disabled="busy===friend.id" @click="add(friend)"><span :class="{online:friend.online}"/>{{ friend.displayName }}<small>{{ friend.online?'在线':'离线' }}</small></button></div></article></div><article class="presence-card email-card"><h3><Mail :size="18"/> 邮件推送</h3><div class="email-grid"><label>SMTP<input v-model="email.host" placeholder="smtp.example.com"/></label><label>端口<input v-model.number="email.port" type="number"/></label><label>加密<select v-model="email.security"><option value="starttls">STARTTLS</option><option value="tls">TLS</option></select></label><label>账号<input v-model="email.username"/></label><label>发件邮箱<input v-model="email.from" type="email"/></label><label>接收邮箱<input v-model="email.to" type="email"/></label><label>授权码<input v-model="email.password" type="password" :placeholder="email.configured?'已安全保存；留空不修改':'SMTP 授权码'"/></label></div><div class="email-actions"><label><input v-model="email.enabled" type="checkbox"/>启用邮件</label><span>{{ message }}</span><button :disabled="busy==='email'" @click="saveEmail(false)">保存</button><button :disabled="busy==='email'" @click="saveEmail(true)">保存并测试</button></div></article><article class="presence-card"><h3>最近投递</h3><div class="delivery-list"><span v-for="item in deliveries.slice(0,12)" :key="item.id"><b :class="item.status">{{ item.status==='sent'?'成功':'失败' }}</b>{{ item.message }} · {{ item.channel==='email'?'邮件':'托盘' }}<small>{{ new Date(item.observedAt).toLocaleString() }}</small></span><span v-if="!deliveries.length" class="empty-compact">暂无记录</span></div></article></section></template>
<style scoped>
.presence-view{display:grid;gap:14px}.presence-toolbar,.presence-toolbar>div,.presence-toolbar label,.email-actions,.email-card h3{display:flex;align-items:center}.presence-toolbar{justify-content:space-between}.presence-toolbar h2{display:flex;align-items:center;gap:8px;margin:0;font-size:20px}.presence-toolbar span{color:var(--muted);font-size:12px}.presence-toolbar label{width:min(360px,45%);gap:8px;padding:9px 11px;border:1px solid var(--line);border-radius:7px;background:var(--surface)}input,select{min-width:0;border:0;outline:0;color:var(--ink);background:transparent}.presence-toolbar input{width:100%}.presence-columns{display:grid;grid-template-columns:1.25fr .75fr;gap:14px}.presence-card{padding:17px;border:1px solid var(--line);border-radius:8px;background:var(--surface)}.presence-card h3{margin:0 0 12px;font-size:15px}.watch-list,.candidate-list,.delivery-list{display:grid;gap:6px;max-height:360px;overflow:auto}.watch-row{display:grid;grid-template-columns:minmax(140px,1fr) repeat(4,auto) 30px;align-items:center;gap:10px;padding:9px;border:1px solid var(--line);border-radius:6px}.watch-row label{display:flex;gap:4px;font-size:12px}.watch-row button{display:grid;place-items:center;height:28px;border:0;color:var(--muted);background:transparent}.candidate-list button{display:grid;grid-template-columns:9px 1fr auto;align-items:center;gap:8px;padding:10px;border:0;border-radius:6px;color:var(--ink);background:var(--surface-muted);text-align:left}.candidate-list button span{width:8px;height:8px;border-radius:50%;background:var(--muted)}.candidate-list button span.online{background:var(--success)}.candidate-list small,.delivery-list small{color:var(--muted)}.email-grid{display:grid;grid-template-columns:2fr .7fr 1fr 1.5fr;gap:9px}.email-grid label{display:grid;gap:5px;color:var(--muted);font-size:11px}.email-grid input,.email-grid select{height:36px;padding:0 9px;border:1px solid var(--line);border-radius:6px;background:var(--surface-muted)}.email-actions{justify-content:flex-end;gap:10px;margin-top:12px}.email-actions label{margin-right:auto}.email-actions button{padding:8px 11px;border:1px solid var(--line-strong);border-radius:6px;color:var(--ink);background:var(--surface-muted)}.delivery-list span{display:grid;grid-template-columns:46px 1fr auto;gap:8px;padding:7px 0;border-bottom:1px solid var(--line);font-size:12px}.delivery-list b{color:var(--success)}.delivery-list b.failed{color:var(--danger)}.empty-compact{padding:16px;color:var(--muted);text-align:center}@media(max-width:900px){.presence-columns,.email-grid{grid-template-columns:1fr}.watch-row{grid-template-columns:1fr repeat(2,auto)}.presence-toolbar{align-items:stretch;flex-direction:column;gap:10px}.presence-toolbar label{width:100%}}
</style>
