<script setup lang="ts">
import { Clock3, Globe2, UserRound } from '@lucide/vue'
interface RecentAccessItem { kind:'friend'|'world'|'avatar'; id:string; title:string; subtitle?:string; imageUrl?:string; openedAt:string }
defineProps<{ items:RecentAccessItem[]; mediaUrl:(value?:string)=>string }>()
const emit=defineEmits<{open:[item:RecentAccessItem]}>()
function time(value:string){return new Intl.DateTimeFormat('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value))}
</script>
<template><section class="recent-access panel wide-view"><header><div><span class="panel-kicker">快速返回</span><h2>最近访问</h2></div><span>仅保存在当前浏览器</span></header><div><button v-for="item in items" :key="`${item.kind}:${item.id}`" @click="emit('open',item)"><img v-if="item.imageUrl" :src="mediaUrl(item.imageUrl)" alt="" /><span v-else><UserRound v-if="item.kind==='friend'" :size="18"/><Globe2 v-else :size="18"/></span><div><strong>{{ item.title }}</strong><small>{{ item.subtitle || (item.kind==='friend'?'好友':'世界') }}</small></div><time><Clock3 :size="11"/>{{ time(item.openedAt) }}</time></button><p v-if="!items.length">打开好友或世界详情后会出现在这里。</p></div></section></template>
<style scoped>.recent-access{padding:0;overflow:hidden}.recent-access>header{display:flex;justify-content:space-between;padding:14px 17px;border-bottom:1px solid var(--line)}header h2{margin:3px 0 0;font-size:14px}header>span{color:var(--muted);font-size:8px}.recent-access>div{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:7px;padding:10px}.recent-access button{display:grid;grid-template-columns:38px 1fr auto;align-items:center;gap:8px;padding:7px;border:1px solid var(--line);border-radius:7px;background:var(--surface-muted);color:var(--ink);text-align:left}.recent-access button:hover{background:var(--surface-hover)}.recent-access img,.recent-access button>span{width:38px;height:38px;border-radius:7px;object-fit:cover}.recent-access button>span{display:grid;place-items:center;background:var(--accent-soft);color:var(--accent)}.recent-access strong,.recent-access small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.recent-access strong{font-size:10px}.recent-access small{margin-top:2px;color:var(--muted);font-size:8px}.recent-access time{display:flex;align-items:center;gap:3px;color:var(--muted);font-size:7px}.recent-access p{color:var(--muted);font-size:9px}</style>
